### PR TITLE
Fix replacement

### PR DESCRIPTION
**Pull request by didiksupriadi41**
Just realize that I did a mistake by replacing all occurrences of `forks` string to `fork` in the URL.

I think just replacing the first occurrence of `forks` should be enough.
What do you think?

### CODE REVIEW

**Comment by FrostyX** [comment]
Or if we want to be extra safe, we can replace `remote + "/forks"` to `remote + "/fork"`?

**Comment by didiksupriadi41** [comment]
I think we could rely on pagure's rule below
so that replacing `/forks/` to `/fork/` is sufficient in this case.

**Project name:**
image

**Group name:**
image

**Comment by FrostyX** [comment]
Cool, that is convincing.

**Comment by FrostyX** [comment]
Thank you!

**Pull request merged**
